### ISSUE TITLE
Create configuration tab for DB connection

### ISSUE THREAD

**Issue by mjbros** [dkoudela/advanced-ldap-for-crucible#2]
The DB connection for this plugin uses the same schema user and password in a different oracle instance from the main DB connection. 

"the database parameters (DB Type, URL, User Name, Password, etc.) are the same as the Crucible DB, except the database name (portion of the DB URL). The parameters are taken from the same source: the Crucible configuration."

In enterprise environments there are restrictions on schema names and related products must be in the same instance because of licensing and disaster recovery requirements.

Can we get a configuration tab for the the DB connection for Advanced LDAP

**Comment by dkoudela** [comment]
There are some considerations why a separate database is used.
It is going to be re-evaluated again during the initiation phase.

Thanks,
David.

**Comment by dkoudela** [comment]
After re-evaluation, it is feasible. 
All supported external database servers can handle crucible and plugin data in one database instance.

HSQL database engine has some general issues with data loss unrelated to the plugin.

Therefore the configuration tab can be made in the next release.

**Comment by mjbros** [comment]
Do you have an ETA on the next release? Is there a dev build that I can test?

**Comment by dkoudela** [comment]
Well, the development is in progress now.
Unfortunately, it is slowed down by urgent issues in other projects.

I have created a Milestone:
https://github.com/dkoudela/advanced-ldap-for-crucible/milestones/Create%20configuration%20tab%20for%20DB%20connection

It should be feasible to finish it in its time frame.

**Comment by mjbros** [comment]
I managed to get  the Oracle instance created so the table is created for the plugin, but now the ldap connection does not work, have you seen this error before?


AdvancedLdapUserManagerImpl.verifyUserCredentials START
**************************** AdvancedLdapConnector EXCEPTION ****************************LDAPException(resultCode=84 (decoding error), errorMessage='The connection to server <ldap server:port > was closed while waiting for a response to a bind request SimpleBindRequest(dn=''):  Unable to read or decode an LDAP message:  Invalid value length of 0 for an ASN.1 integer element.  Integer element values must have a length between 1 and 4 bytes.com.unboundid.asn1.ASN1Exception: Invalid value length of 0 for an ASN.1 integer element.  Integer element values must have a length between 1 and 4 bytes.')
**************************** AdvancedLdapConnector On Finalize ****************************
**************************** AdvancedLdapConnector EXCEPTION on conn closed ****************************java.lang.NullPointerException
AdvancedLdapUserManagerImpl: bind search returned 0 entries

**Comment by dkoudela** [comment]
Hmm, interesting...
It looks like the server has closed the connection before the response is retrieved.
Could you please change "Ldap Page Size" parameter to 10 ?

Could you please tell me what kind of LDAP server you use?

**Comment by dkoudela** [comment]
After several experiments, I am able to simulate the error:
**************************** AdvancedLdapConnector EXCEPTION ****************************LDAPException(resultCode=84 (decoding error), errorMessage='The connection to server 127.0.0.1:8060 was closed while waiting for a response to a bind request SimpleBindRequest(dn=''):  Unable to read or decode an LDAP message:  Invalid value length of 80 for an ASN.1 integer element.  Integer element values must have a length between 1 and 4 bytes.com.unboundid.asn1.ASN1Exception: Invalid value length of 80 for an ASN.1 integer element.  Integer element values must have a length between 1 and 4 bytes.')

This can happen when the plugin connects to a port which provides different protocol.
In this particular case, the port 8060 is http port.

In most cases the port number should be 389.

**Comment by mjbros** [comment]
The ldap server is remove from the FIsheye server. I am using the same URL in the authentication section of Fisheye.

Also, I am using ldaps to connect to the LDAP server.

**Comment by dkoudela** [comment]
Ok, thanks. 
In your case, it looks like a timeout issue.

Does it work if you change "Ldap Page Size" parameter to 10 ?

**Comment by dkoudela** [comment]
I have published a new version 1.3:

**Comment by dkoudela** [comment]
I am closing this issue as the feature has been released.
If you have any question please do not hesitate to reply.

Best Regards,
David.
