### ISSUE TITLE
What is the need for a complete new database?

### ISSUE THREAD

**Issue by chrissy25** [dkoudela/advanced-ldap-for-crucible#3]
Hi,

I wanted to install your plugin on my Crucible instance. But I had to discover, that we need a complete new database to use this plugin. Is there a possibility that I can reuse my old MySQL database without loosing all my data of the database?

Best regards
Chrissy

**Comment by dkoudela** [comment]
Hi,

It is related to the Issue https://github.com/dkoudela/advanced-ldap-for-crucible/issues/2 

There are some considerations why a separate database is used.
It is going to be re-evaluated again during the initiation phase of https://github.com/dkoudela/advanced-ldap-for-crucible/issues/2

Thanks,
David.

**Comment by dkoudela** [comment]
Hi Chrissy,

Yes, it is possible. See Issue #2 
A configuration option will be implemented in the next release.

Best Regards,
David.

**Comment by dkoudela** [comment]
Hi Chrissy,

The configuration option is tracked by the Issue #2 and it will be implemented in the milestone:
https://github.com/dkoudela/advanced-ldap-for-crucible/milestones/Create%20configuration%20tab%20for%20DB%20connection

I am closing this issue for now as a duplicate.
If you have any question please do not hesitate to reply.

Best Regards,
David.
