### ISSUE TITLE
LDAPS tested and working but how to enable?

### ISSUE THREAD

**Issue by isserrano** [dkoudela/advanced-ldap-for-crucible#5]
Hi,
I have the advanced ldap configured for my ldaps service but the service is still using the old ldap config I have in the authentication section. How do I enable the advanced ldap plugin to override the old way?

Thanks

**Comment by dkoudela** [comment]
Hi,

Ldap over SSL is enabled by using ldaps protocol in the URL.

An URL Example:
ldaps://ldap.jumpcloud.com

Best Regards,
David.

**Comment by isserrano** [comment]
Thanks, I had that, but I had to create the properties file and restart the
service for ldaps to work

Ismael

**Comment by dkoudela** [comment]
Hi Ismael,

Ok, is the plugin using ldaps protocol when you change the URL?

FYI, changing the target database in the FECRU property file can change the plugin's target database.

Thanks,
David.

**Comment by isserrano** [comment]
I was using ldap with the normal configuration, not with the plugin. I
installed the plugin and configured it for ldaps. But even with the test
working for the plugin, the login was using the crucible normal
configuration(ldap) no the plugin one.
In summary, what should I do with the crucible authentication config, leave
it empty? put there the same thing as in the plugin?

Thanks for your help

Ismael

**Comment by dkoudela** [comment]
Ok, got it.

You should use the same configuration for the plugin and the FECRU instance.
FECRU configuration is used just for authentication.

These days, it is still required to have both of them.
I have a plan to replace the FECRU authentication functionality later on.

Thanks,
David.

**Comment by isserrano** [comment]
Ok, thanks.

**Comment by dkoudela** [comment]
You are welcome!
