### ISSUE TITLE
How much effort for complete group sync?

### ISSUE THREAD

**Issue by chrissy25** [dkoudela/advanced-ldap-for-crucible#6]
Hi,

you mentioned that the plugin is not able to remove users from a group, when they had been removed in the LDAP group.
How much effort would it be to integrate this functionality, so that we have a complete sync.

BR
Christian

**Comment by dkoudela** [comment]
Hi Christian,

Thank you very much for the issue!

The implementation would not so difficult.
These days, I am finishing a release 1.5 and I do not want to change the scope of the release.
On the other hand, this could be an interesting feature for the next release!

I will consider it in the next release.

Thank you,
David.

**Comment by chrissy25** [comment]
Thank you very much :) 
For our environment it would be very important to have this feature because of security and maintenance reasons :)

**Comment by dkoudela** [comment]
You are welcome! 
Ok, understood. I appreciate your feedback! This is important for the release planing of the product!
Once I get some realistic figures for the next release, I will add a milestone to the issue.

If you have any other feature requests or ideas for improvements do not hesitate to create issues.
I have some ideas how to improve the product but satisfying the customer needs is the priority for me.

**Comment by dkoudela** [comment]
If you would like to try a pre-release version, you can download it from the repository:
http://www.davidkoudela.cz/github/AdvancedLdapForCrucible/target/snapshot/CiBuild61master/advanced-ldap-for-crucible-1.6.jar

You can try it in your test environment.
The feature must be explicitly enabled:

![removingusersfromgroups](https://cloud.githubusercontent.com/assets/7679620/13199090/bfa3b7dc-d81b-11e5-838c-b299c9780372.png)

Any feedback is appreciated.

Thanks,
David.

**Comment by dkoudela** [comment]
Hi Christian,

It has been released in:
https://github.com/dkoudela/advanced-ldap-for-crucible/releases/tag/v1.6

Thanks,
David.
