### ISSUE TITLE
Sync of all users in LDAP

### ISSUE THREAD

**Issue by chrissy25** [dkoudela/advanced-ldap-for-crucible#7]
Hi, 
we would like to implement now this plugin in our Crucible/Fisheye instance. But we are afraid that the plugin will sync all users in our database which would be several 10k.
Will the plugin only sync those users, which are part of the specified groups, or will it sync all users, all groups and will map them afterwards?

We do not have a special attribute on the users, which is telling us that this user is a Fisheye user. We are only able to map it via the AD group they are member of.

Best regards
Christian

**Comment by dkoudela** [comment]
Hi Christian,

There are two parts of the user sync:
1. User sync done by the plugin
2. User sync done by the Crucible/FishEye (FECRU)

Ad.1:
The plugin syncs only LDAP users which are members of the specified LDAP groups.
No other users will be synced.

Ad.2:
These days, the plugin requires usage of the LDAP feature in FECRU only for authentication purposes. User sync done by the FECRU is not needed.

To avoid syncing unwanted users, I would suggest configuring the FECRU this way (Authentication Settings):
_Auto-add: Users must be added to FishEye manually_
_Periodically synchronise users with LDAP: No (you can still manually sync from the Security page)_

![fecru-no-sync](https://cloud.githubusercontent.com/assets/7679620/15173257/5e9fee04-175b-11e6-9a61-8a27db3d6614.png)

Also, you must not click on the Re-Sync button on the FECRU Authentication page:
![fecru-re-sync](https://cloud.githubusercontent.com/assets/7679620/15173370/f902cd68-175b-11e6-8bbb-d784c03facae.png)

Additionally, you can configure your LDAP server to provide larger responses in LDAP pages. 
As FECRU 3.x does not work with LDAP paged responses, it will not sync high number of users even when you click on the Re-Sync button on the FECRU Authentication page.



Moreover, I would suggest testing the setup on a testing FECRU instance before it is applied on the production systems.
We also do it this way. We also have high number of LDAP users and only small portion of them have access to our repos/projects in our FECRU instances.

If you find any issue, I am here to help you.

Best Regards,
David.

**Comment by dkoudela** [comment]
Hi Christian,

I am closing the issue for now.
If you have any other question, please, do not hesitate to ask.

Thanks,
David.
